//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBoard.UedWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/", ConfigurationName="UedWs.UEDWSPortType")]
    public interface UEDWSPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#isWebserviceEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool isWebserviceEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getAuthorizationKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAuthorizationKey(string username, string password, string deviceIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#revokeAuthorizationKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool revokeAuthorizationKey(iBoard.UedWs.UedCredentials credentials, string deviceIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#validateCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool validateCredentials(iBoard.UedWs.UedCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#unixTimestampToUedDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        iBoard.UedWs.UedDate unixTimestampToUedDate(iBoard.UedWs.UedCredentials credentials, string timeStamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#_uedDateToUnixTimestamp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string _uedDateToUnixTimestamp(iBoard.UedWs.UedCredentials credentials, iBoard.UedWs.UedDate uedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#uedDateToUnixTimestamp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string uedDateToUnixTimestamp(iBoard.UedWs.UedCredentials credentials, iBoard.UedWs.UedDate uedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getMyCourses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UedCourse[] getMyCourses(iBoard.UedWs.UedCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#canAccessToCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool canAccessToCourse(iBoard.UedWs.UedCredentials credentials, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getCourseRecentEnrolments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UedRecentEnrolment[] getCourseRecentEnrolments(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getCourseRecentModifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UedRecentModification[] getCourseRecentModifications(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getCourseRecentForumActivity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UedRecentForumActivity[] getCourseRecentForumActivity(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getUserPublicProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        iBoard.UedWs.UedUser getUserPublicProfile(iBoard.UedWs.UedCredentials credentials, int userId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getMyUserPublicProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        iBoard.UedWs.UedUser getMyUserPublicProfile(iBoard.UedWs.UedCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UEDWS#UEDWSServer#getVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentForumActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentModification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedRecentEnrolment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UedCourse))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getVersion();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string autorizationKeyField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        public string autorizationKey {
            get {
                return this.autorizationKeyField;
            }
            set {
                this.autorizationKeyField = value;
                this.RaisePropertyChanged("autorizationKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string fullNameField;
        
        private string imageUrlField;
        
        private string descriptionField;
        
        private string countryField;
        
        private string cityField;
        
        private string webPageUrlField;
        
        private string profileLinkField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("imageUrl");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        public string webPageUrl {
            get {
                return this.webPageUrlField;
            }
            set {
                this.webPageUrlField = value;
                this.RaisePropertyChanged("webPageUrl");
            }
        }
        
        /// <remarks/>
        public string profileLink {
            get {
                return this.profileLinkField;
            }
            set {
                this.profileLinkField = value;
                this.RaisePropertyChanged("profileLink");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedForumActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string discussionTypeField;
        
        private int parentIdField;
        
        private int discussionIdField;
        
        private int userIdField;
        
        private UedDate dateField;
        
        private int postIdField;
        
        private string postSubjectField;
        
        private string postUrlField;
        
        /// <remarks/>
        public string discussionType {
            get {
                return this.discussionTypeField;
            }
            set {
                this.discussionTypeField = value;
                this.RaisePropertyChanged("discussionType");
            }
        }
        
        /// <remarks/>
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("parentId");
            }
        }
        
        /// <remarks/>
        public int discussionId {
            get {
                return this.discussionIdField;
            }
            set {
                this.discussionIdField = value;
                this.RaisePropertyChanged("discussionId");
            }
        }
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        public UedDate date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        public int postId {
            get {
                return this.postIdField;
            }
            set {
                this.postIdField = value;
                this.RaisePropertyChanged("postId");
            }
        }
        
        /// <remarks/>
        public string postSubject {
            get {
                return this.postSubjectField;
            }
            set {
                this.postSubjectField = value;
                this.RaisePropertyChanged("postSubject");
            }
        }
        
        /// <remarks/>
        public string postUrl {
            get {
                return this.postUrlField;
            }
            set {
                this.postUrlField = value;
                this.RaisePropertyChanged("postUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hourField;
        
        private string minuteField;
        
        private string secondField;
        
        private string dayField;
        
        private string monthField;
        
        private string yearField;
        
        /// <remarks/>
        public string hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
                this.RaisePropertyChanged("hour");
            }
        }
        
        /// <remarks/>
        public string minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
                this.RaisePropertyChanged("minute");
            }
        }
        
        /// <remarks/>
        public string second {
            get {
                return this.secondField;
            }
            set {
                this.secondField = value;
                this.RaisePropertyChanged("second");
            }
        }
        
        /// <remarks/>
        public string day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("day");
            }
        }
        
        /// <remarks/>
        public string month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedRecentForumActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int forumIdField;
        
        private string forumNameField;
        
        private int sectionNumberField;
        
        private UedForumActivity[] activityField;
        
        /// <remarks/>
        public int forumId {
            get {
                return this.forumIdField;
            }
            set {
                this.forumIdField = value;
                this.RaisePropertyChanged("forumId");
            }
        }
        
        /// <remarks/>
        public string forumName {
            get {
                return this.forumNameField;
            }
            set {
                this.forumNameField = value;
                this.RaisePropertyChanged("forumName");
            }
        }
        
        /// <remarks/>
        public int sectionNumber {
            get {
                return this.sectionNumberField;
            }
            set {
                this.sectionNumberField = value;
                this.RaisePropertyChanged("sectionNumber");
            }
        }
        
        /// <remarks/>
        public UedForumActivity[] activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("activity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedRecentModification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string operationField;
        
        private string textField;
        
        private string moduleField;
        
        private string modulenameField;
        
        private string urlField;
        
        private UedDate dateField;
        
        /// <remarks/>
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("module");
            }
        }
        
        /// <remarks/>
        public string modulename {
            get {
                return this.modulenameField;
            }
            set {
                this.modulenameField = value;
                this.RaisePropertyChanged("modulename");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public UedDate date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedRecentEnrolment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private int courseIdField;
        
        private string userFullNameField;
        
        private string userProfileLinkField;
        
        private UedDate dateField;
        
        /// <remarks/>
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        public int courseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
                this.RaisePropertyChanged("courseId");
            }
        }
        
        /// <remarks/>
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
                this.RaisePropertyChanged("userFullName");
            }
        }
        
        /// <remarks/>
        public string userProfileLink {
            get {
                return this.userProfileLinkField;
            }
            set {
                this.userProfileLinkField = value;
                this.RaisePropertyChanged("userProfileLink");
            }
        }
        
        /// <remarks/>
        public UedDate date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ead.ipleiria.pt/admin/report/uedws/")]
    public partial class UedCourse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string shortNameField;
        
        private int idNumberField;
        
        private int categoryField;
        
        private string fullNameField;
        
        private int visibleField;
        
        private string newsItemsField;
        
        private string fullLinkField;
        
        private UedDate startDateField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("shortName");
            }
        }
        
        /// <remarks/>
        public int idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        public int category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        public int visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
                this.RaisePropertyChanged("visible");
            }
        }
        
        /// <remarks/>
        public string newsItems {
            get {
                return this.newsItemsField;
            }
            set {
                this.newsItemsField = value;
                this.RaisePropertyChanged("newsItems");
            }
        }
        
        /// <remarks/>
        public string fullLink {
            get {
                return this.fullLinkField;
            }
            set {
                this.fullLinkField = value;
                this.RaisePropertyChanged("fullLink");
            }
        }
        
        /// <remarks/>
        public UedDate startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UEDWSPortTypeChannel : iBoard.UedWs.UEDWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UEDWSPortTypeClient : System.ServiceModel.ClientBase<iBoard.UedWs.UEDWSPortType>, iBoard.UedWs.UEDWSPortType {
        
        public UEDWSPortTypeClient() {
        }
        
        public UEDWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UEDWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UEDWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UEDWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isWebserviceEnabled() {
            return base.Channel.isWebserviceEnabled();
        }
        
        public string getAuthorizationKey(string username, string password, string deviceIdentification) {
            return base.Channel.getAuthorizationKey(username, password, deviceIdentification);
        }
        
        public bool revokeAuthorizationKey(iBoard.UedWs.UedCredentials credentials, string deviceIdentification) {
            return base.Channel.revokeAuthorizationKey(credentials, deviceIdentification);
        }
        
        public bool validateCredentials(iBoard.UedWs.UedCredentials credentials) {
            return base.Channel.validateCredentials(credentials);
        }
        
        public iBoard.UedWs.UedDate unixTimestampToUedDate(iBoard.UedWs.UedCredentials credentials, string timeStamp) {
            return base.Channel.unixTimestampToUedDate(credentials, timeStamp);
        }
        
        public string _uedDateToUnixTimestamp(iBoard.UedWs.UedCredentials credentials, iBoard.UedWs.UedDate uedDate) {
            return base.Channel._uedDateToUnixTimestamp(credentials, uedDate);
        }
        
        public string uedDateToUnixTimestamp(iBoard.UedWs.UedCredentials credentials, iBoard.UedWs.UedDate uedDate) {
            return base.Channel.uedDateToUnixTimestamp(credentials, uedDate);
        }
        
        public UedCourse[] getMyCourses(iBoard.UedWs.UedCredentials credentials) {
            return base.Channel.getMyCourses(credentials);
        }
        
        public bool canAccessToCourse(iBoard.UedWs.UedCredentials credentials, int courseId) {
            return base.Channel.canAccessToCourse(credentials, courseId);
        }
        
        public UedRecentEnrolment[] getCourseRecentEnrolments(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate) {
            return base.Channel.getCourseRecentEnrolments(credentials, courseId, UedStartDate);
        }
        
        public UedRecentModification[] getCourseRecentModifications(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate) {
            return base.Channel.getCourseRecentModifications(credentials, courseId, UedStartDate);
        }
        
        public UedRecentForumActivity[] getCourseRecentForumActivity(iBoard.UedWs.UedCredentials credentials, int courseId, iBoard.UedWs.UedDate UedStartDate) {
            return base.Channel.getCourseRecentForumActivity(credentials, courseId, UedStartDate);
        }
        
        public iBoard.UedWs.UedUser getUserPublicProfile(iBoard.UedWs.UedCredentials credentials, int userId, int courseId) {
            return base.Channel.getUserPublicProfile(credentials, userId, courseId);
        }
        
        public iBoard.UedWs.UedUser getMyUserPublicProfile(iBoard.UedWs.UedCredentials credentials) {
            return base.Channel.getMyUserPublicProfile(credentials);
        }
        
        public string getVersion() {
            return base.Channel.getVersion();
        }
    }
}
