//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted.
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account elimination.
        /// </summary>
        public static string AccountElimination {
            get {
                return ResourceManager.GetString("AccountElimination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new moodle account:.
        /// </summary>
        public static string AddMoodleAccount {
            get {
                return ResourceManager.GetString("AddMoodleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this account?.
        /// </summary>
        public static string AreYouSureThatYouWantToDeleteTheAccount {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantToDeleteTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration exported successfuly.
        /// </summary>
        public static string ConfigurationExportedSuccessfuly {
            get {
                return ResourceManager.GetString("ConfigurationExportedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file.
        /// </summary>
        public static string ConfigurationFile {
            get {
                return ResourceManager.GetString("ConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loaded.
        /// </summary>
        public static string ConfigurationLoaded {
            get {
                return ResourceManager.GetString("ConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loaded successfuly.
        /// </summary>
        public static string ConfigurationLoadedSuccessfuly {
            get {
                return ResourceManager.GetString("ConfigurationLoadedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on configuration restore.
        /// </summary>
        public static string ConfigurationRestoreError {
            get {
                return ResourceManager.GetString("ConfigurationRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loss warning.
        /// </summary>
        public static string DataLossWarning {
            get {
                return ResourceManager.GetString("DataLossWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while exporting the configuration.
        /// </summary>
        public static string ErrorExportingConfiguration {
            get {
                return ResourceManager.GetString("ErrorExportingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred: {0}.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on XML validation against the schema.
        /// </summary>
        public static string ErrorOnXmlValidationAgainstTheSchema {
            get {
                return ResourceManager.GetString("ErrorOnXmlValidationAgainstTheSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the configuration.
        /// </summary>
        public static string ErrorWhileLoadingTheConfiguration {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingTheConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the configuration file.
        /// </summary>
        public static string SelectTheConfigurationFile {
            get {
                return ResourceManager.GetString("SelectTheConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As requested, the account was successfuly deleted.
        /// </summary>
        public static string TheAccountWasDeletedAsRequested {
            get {
                return ResourceManager.GetString("TheAccountWasDeletedAsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will replace any previous configuration file. Are you sure that you want to continue?.
        /// </summary>
        public static string ThisOperationWillReplaceTheConfigurationFile {
            get {
                return ResourceManager.GetString("ThisOperationWillReplaceTheConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to terminate your session?.
        /// </summary>
        public static string ThisWillTerminateYourSession {
            get {
                return ResourceManager.GetString("ThisWillTerminateYourSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the account. Please try again later..
        /// </summary>
        public static string UnableToDeleteTheAccount {
            get {
                return ResourceManager.GetString("UnableToDeleteTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select the XML node to set.
        /// </summary>
        public static string UnableToSelectTheXmlNodeToSet {
            get {
                return ResourceManager.GetString("UnableToSelectTheXmlNodeToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update moodle account:.
        /// </summary>
        public static string UpdateMoodleAccount {
            get {
                return ResourceManager.GetString("UpdateMoodleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account already exists in the user profile.
        /// </summary>
        public static string UserAccountAlreadyExists {
            get {
                return ResourceManager.GetString("UserAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identifier doesn&apos;t exists on the configuration XML.
        /// </summary>
        public static string UserIdDontExist {
            get {
                return ResourceManager.GetString("UserIdDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file wasn&apos;t been found.
        /// </summary>
        public static string XmlFileNotFound {
            get {
                return ResourceManager.GetString("XmlFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML Schema file wasn&apos;t been found.
        /// </summary>
        public static string XmlSchemaFileNotFound {
            get {
                return ResourceManager.GetString("XmlSchemaFileNotFound", resourceCulture);
            }
        }
    }
}
